spring.application.name=userEmail

server.port=8081

spring.datasource.url= jdbc:postgresql://localhost:5432/email-user
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.addresses=amqps://mtciaxbb:sQko8c4PwaZhdGj0yhRqRp0BWbq7QJqj@jaragua.lmq.cloudamqp.com/mtciaxbb
#nome da fila
spring.rabbitmq.queue=envio.email
